### PR TITLE
add privacy provider

### PR DESCRIPTION
**Pull request by olive007**
GPDR compliant

### CODE REVIEW

**Comment by woolardfa** [comment]
Thank you for submitting this pull request to establish GDPR compliance. I will review it as quickly as possible and respond.

**Comment by woolardfa** [comment]
I would be happy to merge your changes but for a few fixes: line 28 in provider.php should be removed; the version number should be 2013052008, and the release should be "0.0.8 (Build 2018072600)"

**Comment by olive007** [comment]
Done

**Review by woolardfa — APPROVED** [review]
That's dandy! Thanks.

**Pull request merged**
